@Identity.App_HostAddress = http://localhost:5256

POST {{Identity.App_HostAddress}}/api/login
Content-Type: application/json
Accept: application/json
{
    "email": "admin@localhost",
    "password": "Azerty123$"
} 

###
