/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountOverview: typeof import('./components/Account/AccountOverview.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Divider: typeof import('primevue/divider')['default']
    InputOtp: typeof import('primevue/inputotp')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LabelInput: typeof import('./components/LabelInput.vue')['default']
    LoginForm: typeof import('./components/Login/LoginForm.vue')['default']
    Password: typeof import('primevue/password')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
